---
# Source: helm for kubernetes/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: loyloy
  labels:
    app: loyloy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loyloy
  template:
    metadata:
      labels:
        app: loyloy
    spec:
      containers:
        - name: loyloy
          image: docker.io/phengbunath/loyloy:3
          imagePullPolicy: Always
          ports:
            - containerPort: 8080